baseURL = 'https://example.org/'
languageCode = 'en-us'
# title = 'Aiko Bormann'
theme = 'port'

############################## navigation ###############################

# main menu
[[menu.main]]
name = "Home"
URL = "#header"
weight = 1

[[menu.main]]
name = "Videos"
URL = "#videos"
weight = 2

[[menu.main]]
name = "Bilder"
URL = "#pictures"
weight = 3

[[menu.main]]
name = "Über mich"
URL = "#about"
weight = 4

[[menu.main]]
name = "Kontakt"
URL = "#about"
weight = 5

#################### default parameters ################################
[params]
copyright = "Copyright Aiko Bormann &copy;"
# Meta data
description = "Personal Portfolio"
author = "Pedro Scaff"
favicon = "images/favicon.png"

[[params.social]]
icon = "fas fa-envelope"
link = "mailto:aikobormann@gmail.com"
############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "vendor/css/bootstrap.min.css"
[[params.plugins.css]]
link = "vendor/fontawesome/css/all.min.css"
[[params.plugins.css]]
link = "vendor/css/hover-min.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap"
[[params.plugins.css]]
link = "plugins/text-animation/text-animation.css"
[[params.plugins.css]]
link = "plugins/hugrid/hugrid.css"

# JS Plugins
[[params.plugins.js]]
link = "vendor/js/jquery-3.5.1.min.js"
[[params.plugins.js]]
link = "vendor/js/jquery.waypoints.js"
[[params.plugins.js]]
link = "plugins/text-animation/text-animation.js"
[[params.plugins.js]]
link = "plugins/hugrid/hugrid.min.js"
